### ISSUE TITLE
form validation issue

### ISSUE THREAD

**Issue by om-bhutkar-05** [om-bhutkar-05/studentregistration#1]
Even though , the input fields are marked as required in the interface of this website the form is submitting empty inputs , someone please address this issue and fix this bug

**Comment by aman-rangari** [comment]
The following issue has been addressed successfully by adding validation checks using js , now the form raises alert if any of the marked field is empty!.

**Comment by aman-rangari** [comment]
The following issue has been addressed successfully by adding validation checks using js , now the form raises alert if any of the marked field is empty!.
