### ISSUE TITLE
The CSV isnt accessible

### ISSUE THREAD

**Issue by om-bhutkar-05** [om-bhutkar-05/studentregistration#4]
even though Data is getting stored in a CSV at backend it isnt accessible for anyone other than the host , therefore  please add a download button to download a copy of csv , and to maintain integrity ask for some password for initializing the download!.

**Comment by ishaKhutafale** [comment]
I’ve added a download button for the CSV file. To ensure data integrity, users now need to enter a password before downloading. This way, only authorized users can access the file.
